services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: image-lista_super:latest
    restart: unless-stopped
    container_name: container-lista_super
    ports:
      - "13000:80"